services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://root:${DB_PASSWORD}@database:3306/${DB_NAME}?serverVersion=8.0
      - APP_ENV=dev  
      - APP_SECRET=your-secret-key
      - CORS_ALLOW_ORIGIN=http://localhost:3000
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./backend:/app  

  frontend:
    build: ./frontend
    ports:
      - "3000:80"  
    environment:
      - REACT_APP_API_URL=http://localhost:8000  
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  db_data:

networks:
  app-network:
    driver: bridge